# Generated by Django 4.2.7 on 2023-12-06 21:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignmentId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('dueDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('enrollmentCapacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(default='', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', 'Only alphanumeric characters are allowed.')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dateJoined', models.DateField(auto_now_add=True)),
                ('role', models.CharField(max_length=20)),
                ('email_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submissionId', models.AutoField(primary_key=True, serialize=False)),
                ('submissionContent', models.TextField()),
                ('submissionDate', models.DateField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('materialId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('uploadDate', models.DateField(auto_now_add=True)),
                ('documentType', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.course')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('gradeId', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=10)),
                ('feedback', models.TextField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.customuser'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.course'),
        ),
    ]
