# Generated by Django 4.2.7 on 2023-12-06 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_readingstate_interactionhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='userId',
            new_name='id',
        ),
    ]
