# Generated by Django 4.2.7 on 2023-12-07 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_rename_userid_customuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
