# Generated by Django 4.2.7 on 2023-12-07 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
