# Generated by Django 4.2.7 on 2023-12-06 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_portal', '0005_customuser_alter_course_tutor_alter_grade_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='material',
            name='course',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='student',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
